title: Today I <verbed>
description: Thomas Aamand Witting
url: "https://thwit.github.io"
baseurl: ""

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
remote_theme: daviddarnes/garth
plugins:
  - jekyll-remote-theme

# Theme override
logo: /assets/images/logo.svg